### ISSUE TITLE
"user defined" adress line is missing

### ISSUE THREAD

**Issue by MichaelMeier99** [speedball2001/identitychooser-mx#1]
Thank you for this great add-on.
It has only one issue to me: If I choose "from", my addresses are prompted one below the other.
WITHOUT the add-on the very last line allows me to key in an address by hand.
WITH the add-on this very last line is waved.
Do you think, you can do something, that this -for me- very useful line/options stays there?
Thank you!
![adressChooser](https://user-images.githubusercontent.com/49785471/93668802-5154ca00-fa8f-11ea-8702-dac5832e5c93.png)

**Comment by speedball2001** [comment]
This is an issue with Identity Chooser version 1.99 and older. 

Version 2.0, which only works with Thunderbird 78 though, doesn't manipulate this drop down menu anymore, thus, letting you enter a from address by hand.
