### ISSUE TITLE
Feature request,  Automatic sender selection according to recipient?

### ISSUE THREAD

**Issue by jprykiel** [speedball2001/identitychooser-mx#13]
Hi speedball.
I don't know yet if identity chooser  already does this, but it would be really cool to have your sender selected automatically after typing your recipient's address. This already existed in an add-on I use a while ago called correct identity, but which is not compatible with today's Thunderbird versions.
What do you say?
Cheers,
JPR

**Comment by speedball2001** [comment]
Thank you for the feature request. This is not possible with Identity Chooser. Identity Chooser's idea is to explicitely force you to select the sender address before even opening the email editor. It wont have features that automate sender selection.
