### ISSUE TITLE
Show IC emnu on keyboard shortcuts

### ISSUE THREAD

**Issue by elhennig** [speedball2001/identitychooser-mx#14]
Can the keyboard shortcuts (CTRL-l, CTRL-r, CTRL-R) be activated in any way?
Only CTRL-N works at it uses the Compose button from the main buttons, but reply-to, reply-to-all and forward do not yet work with keyboard shortcuts.

**Comment by speedball2001** [comment]
Do you use the main toolbar buttons or the ones in the email header?

**Comment by speedball2001** [comment]
Please try out version 2.1beta4 (https://github.com/speedball2001/identitychooser-mx/releases/tag/2.1beta4). It implements shortcuts as long as you add the forward/reply/replyall buttons to the main toolbar.

**Comment by speedball2001** [comment]
I released Identity Chooser 2.1 and submitted the new version to addons.thunderbird.net. Version 2.1 fixes this bug.
