### ISSUE TITLE
Shift to toggle message format (plain/HTML) no longer works with Identity Chooser

### ISSUE THREAD

**Issue by Annihilannic** [speedball2001/identitychooser-mx#15]
Hi, subject says it all.  I'm using Identity Chooser 2.0, ThunderBird 78.5.0 (32-bit), Windows 10 64-bit.

This definitely used to work in the past.  i.e. if you have your default send format set to HTML, shift-reply would send plain text, and vice versa.

**Comment by speedball2001** [comment]
This is a bug in Thunderbird 78 itself unfortunately (see https://bugzilla.mozilla.org/show_bug.cgi?id=1658132). There's not much that I can do about, unfortunately.

**Comment by Annihilannic** [comment]
Well, now that bug has 1 vote, and a way of tracking it here as well! ;-)  Thanks

**Comment by speedball2001** [comment]
Either it's coincidental or your vote set things into motion. The bug got a lot of activity yesterday.

**Comment by Annihilannic** [comment]
Midas touch! ;-)

**Comment by speedball2001** [comment]
Thunderbird 78.7 came out today. It seems that they fixed this issue. Can you confirm that it works for you now?

**Comment by Annihilannic** [comment]
Yes, working perfectly now.  :-)
