### ISSUE TITLE
Keyboard shortcut Ctrl-R and Ctrl-Shift-R does not work on version 2.1

### ISSUE THREAD

**Issue by magic-engineer** [speedball2001/identitychooser-mx#17]
I'm experiencing that keyboard shortcut Ctrl-R and Ctrl-Shift-R does not work on version 2.1.
Is this intentionally implemented on this version?
It was working on version 2.0.

**Comment by speedball2001** [comment]
Can you explain what doesn't work? I did changes to Ctrl-R and Ctrl-Shift-R. This is what is supposed to happen:

- If you have the Reply and Reply All buttons enabled in Thunderbird's main toolbar  it should open the identity menu of these buttons
- If you don't have these toolbar buttons enabled, Ctrl-R and Ctrl-Shift-R should work as they always did.

At least that how it works in my environment.

Could you please restart Thunderbird and test if that fixes the issue?

**Comment by magic-engineer** [comment]
Thank you very much for the explanation.

I tested to verify this works, with enabling these buttons in toolbar>
- If you have the Reply and Reply All buttons enabled in Thunderbird's main toolbar it should open the identity menu of these buttons

However, this seems not working, with removing these buttons from toolbar (it is the original setting of my Thunderbird)>
- If you don't have these toolbar buttons enabled, Ctrl-R and Ctrl-Shift-R should work as they always did.

I'm not sure if this only happens in Japanese version Thunderbird though...
Without Reply, Reply All buttons in toolbar, Ctrl-R and Ctrl-Shift-R does not open anything in my environment.

By the way, I just want to confirm that "main toolbar" means the space where cursor is pointing in this picture?

![20201216SS00001](https://user-images.githubusercontent.com/8553895/102332691-c4f36e00-3fcf-11eb-8531-e8f1ff3eaf86.png)

**Comment by speedball2001** [comment]
Yes that's Thunderbird's main toolbar.

Anyway, I could reproduce the issue on my side and I think I fixed the bug. Please test the new beta version (https://github.com/speedball2001/identitychooser-mx/releases/tag/2.2beta1) and let me know if it works for you.

**Comment by magic-engineer** [comment]
Thank you very much!

I've just checked the 2.2 beta 1 and I think it is working very good!!

**Comment by speedball2001** [comment]
I released version 2.2 and submitted it to addons.thunderbird.net. You'll automatically receive the update after it passed the review process.
