### ISSUE TITLE
Quoted text is ignored

### ISSUE THREAD

**Issue by LeslieDesser** [speedball2001/identitychooser-mx#22]
Superb tool but it is ignoring any text quoting on a reply.

Normally I reply to emails by highlighting some text and then click Reply.  (Bottom posting)

With this add-on enabled, my highlighting is ignored and each time the whole email is being quoted.

**Comment by KevinALinden** [comment]
In addition to this behavior: If I open an email in a SEPARATE WINDOW, and then hit that window's REPLY button, this will cause a _totally different email's text_ to be automatically quoted in the reply, this totally different email being whatever one is open in Thunderbird's MAIN window. Disabling the extension fixes this problem.

**Comment by speedball2001** [comment]
@KevinALinden This is a different issue. I opened a separate bug for this, please consider subscribing to that one (as well).

**Comment by speedball2001** [comment]
@LeslieDesser The MailExtension functionality for composing/replying/forwarding has several issues. There are fixes incoming in the next version of Thunderbird, 78.7.

Let's wait for this version and see if it fixes this issue as well. If it doesn't, I'll look into it. Feel free to ping this issue/me after TB78.7 was released.

**Comment by LeslieDesser** [comment]
I checked beta1 for issue #23 and it does not fix this problem.

**Comment by speedball2001** [comment]
#23 is not supposed to fix the quoting issue. I'll wait for TB78.8 which may fixed it.

**Comment by LeslieDesser** [comment]
Installed 78.8.0 but the bug is still there.

**Comment by speedball2001** [comment]
I dug through Thunderbird's source code. The reply code that addons/mailextension such as Identity Chooser have to use is different from the code that the default reply button uses. 

There's currently nothing I can do about that. I'll have to open a bug with Thunderbird but have to develop a minimal test case demonstrating the issue first. I'll see if I find time to do that.

**Comment by speedball2001** [comment]
This should be fixed with Identity Chooser 4.0.
