### ISSUE TITLE
If I open an email in a SEPARATE WINDOW hitting that window's REPLY button quotes a different email

### ISSUE THREAD

**Issue by speedball2001** [speedball2001/identitychooser-mx#23]
In addition to this behavior: If I open an email in a SEPARATE WINDOW, and then hit that window's REPLY button, this will cause a _totally different email's text_ to be automatically quoted in the reply, this totally different email being whatever one is open in Thunderbird's MAIN window. Disabling the extension fixes this problem.

_Originally posted by @KevinALinden in https://github.com/speedball2001/identitychooser-mx/issues/22#issuecomment-765736885_

**Comment by speedball2001** [comment]
The issue should be fixed in [release 2.3beta1](https://github.com/speedball2001/identitychooser-mx/releases/tag/2.3beta1)

**Comment by speedball2001** [comment]
Release 2.3beta1 doesn't quite fix the issue. It now might disable replying from the main window.

Steps to reproduce:

- Start Thunderbird
- Select an email
- Press reply --> An editor window opens as expected
- Close the editor
- Now open the email in it's own window
- Presse reply -->An editor window opens as expected
- Close both windows (reply editor and original) email
- Back in Thunderbird's main window: click on reply --> Nothing happens

**Comment by jnmills** [comment]
See also issue #44

**Comment by speedball2001** [comment]
This issue should be fixed in Identity Chooser 4.0.
