### ISSUE TITLE
addon breaks the "Catch all" address feature

### ISSUE THREAD

**Issue by CircleCode** [speedball2001/identitychooser-mx#24]
With https://bugzilla.mozilla.org/show_bug.cgi?id=1518025, thunderbird added a new feature allowing to dynamically replace the "from" field with the one the mail responded to was addressed.
This includes 2 parts:
1. dynamically choosing the corresponding identity (this is indeed in conflict with the features of this addon)
2. replacing the "from" field when the matching identity is marked as "catch all" (i.e. `reply from this identity when delivering headers match` is checked, and its value is `*@domain`)

It would be awesome if, when choosing a "catch all" identity, the from field was correctly replaced with the native thunderbird feature.

If this is not possible (which I suspect), I suppose a simple config option to disable identitychooser when replying / forwarding may be sufficient.

**Comment by speedball2001** [comment]
You can disable Identity Chooser for replying and forwarding in Identity Chooser' settings. You find the settings in the addon manager when you click on the 3 dots next to the enabled/disable switch.

**Comment by CircleCode** [comment]
sorry I missed this settings window, it indeed does the job.
Out of curiosity, do you think it is possible to have the native _dynamic `from`_ feature while keeping Identity Chooser enabled for reply?

**Comment by speedball2001** [comment]
> sorry I missed this settings window, it indeed does the job.

It is a bit hidden, but I can't do anything about that. It's where Thunderbird places these, unfortunately.

> Out of curiosity, do you think it is possible to have the native _dynamic `from`_ feature while keeping Identity Chooser enabled for reply?

It's out of scope, to be honest. It's still unclear to me where Thunderbird will go when it comes to future addon functionality. I'd like to keep the feature set minimal for the time being.

**Comment by CircleCode** [comment]
> It is a bit hidden, but I can't do anything about that. It's where Thunderbird places these, unfortunately.

I definitely should have checked before asking for options

> It's out of scope

Fine for me, the current set of feature is working for me, thanks
