### ISSUE TITLE
Theme issue

### ISSUE THREAD

**Issue by mbnoimi** [speedball2001/identitychooser-mx#25]
As shown below I use the dark theme in Linux Mint 20.1. The whole identity area is unreadable!
![image](https://user-images.githubusercontent.com/284547/106742008-81ab9800-662d-11eb-99d1-836ad75575ab.png)
May you please take a look into this issue?

**Comment by speedball2001** [comment]
Please choose a different identity color in Identity Chooser's settings. You find the settings in the addon manager when you click on the 3 dots next to the enabled/disable switch.

**Comment by mbnoimi** [comment]
Works fine; Sorry for the silly question.
