### ISSUE TITLE
Write, Reply & Reply All dropdowns stop working if user account identity deleted

### ISSUE THREAD

**Issue by ev0net** [speedball2001/identitychooser-mx#28]
Thanks for making this plugin! I've appreciated it for years. I finally just upgraded thunderbird after years of hesitancy about loosing some old plugins and installed the tb78 version. I deleted some identities and Write, Reply & Reply All dropdowns stop working. I restarted TB and disabled then reenabled the plugin, but the workaround was uninstalling and reinstalling, which of course, deleted all my settings. Seems like bug that's easy to replicate. Thanks again!

**Comment by githwithit** [comment]
I am in a similar situation as ev0net.

I was at TB38 and now have upped to 78.10.2 (64-bit) on Windows 7 and I can not get the dropdowns to work no matter what.

I've tried disable/enable many times, restarting, etc with no success. I've also removed all other add ons but still no joy.

I wonder if I have some old configuration parameters which I can't see/access have caused an issue with the new layout engine and/or the new add on architecture.

I'll leave it installed and hope a future version makes it pop back to life. This is a super handy add on, thanks for making it!

**Comment by softfoot** [comment]
Hmmm, I may have the same problem ... I deleted an old profile but then TB updated to 78.12.0 (64-bit) so I'm not sure of the real cause.
Either way it doesnt present any dropdowns and restarting/reinstalling did not help.
Shame its a vital addon for me.
Regards,
Dave

**Comment by bege10** [comment]
@speedball2001 Would you, please, have a look at this issue? It still persists.
In TB v91.5.1 I deleted an account and now the dropdown button has vanished and in the extension settings several identities are missing.
Restarting TB and un- and reactivating the extension don't help.

**Comment by MoralCode** [comment]
i believe i have also experienced this issue in TB 91.13.0 with extension version 3.1 the extension is no longer prompting which account to use when creating emails or replying. i didnt think it was related to deleting an account until reading this issue.

the error console is showing an error `TypeError: identity is undefined [background.js:41:51]` for me. maybe thats helpful?

**Comment by speedball2001** [comment]
Anybody who experienced this bug: Please test version [3.2beta2](https://github.com/speedball2001/identitychooser-mx/releases/tag/3.2beta2) and report back. Thanks to @MoralCode this should be fixed.

**Comment by MoralCode** [comment]
I also think i found another workaround that I'd like to know if it works for people. Does changing a setting related to the identities (order, whether they are shown) and saving (and optionally reverting the change) also resolve the issue (see the comments on the linked PR)?
