### ISSUE TITLE
Disappearing functionality of the add-on in TB 78.3.x (32bit)

### ISSUE THREAD

**Issue by ienae** [speedball2001/identitychooser-mx#3]
When TB is started, Identity Chooser 2.0 is not working, although properly installed and visible in the add-ons manager of TB. 
Only disabling/enabling the add-on brings back its functionality - the arrows on the write / forward /reply buttons are visible and fully functional. However, after ending the TB session, the same problem appears again at a restart. No arrows and functionality. 
Even a complete uninstall and re-install of the add-on did not solve the problem.

**Comment by hopalongrock** [comment]
Exactly. I can confirm this. Thanks for the disable/enable trick.

2,0beta1 works fine.

**Comment by speedball2001** [comment]
> 2,0beta1 works fine.

That's a good hint. I'll look into what may have changed between these versions.

Just for reference: Do you have any other addons installed?

**Comment by hopalongrock** [comment]
Yes, I have many

My add-ons:
[addons.zip](https://github.com/speedball2001/identitychooser-mx/files/5377303/addons.zip)

**Comment by speedball2001** [comment]
Quick update: It looks like this issue is a difficult to debug race condition. I've experienced it once just a day ago but can't reliably reproduce it yet.

**Comment by ienae** [comment]
Thanks for your update. The reliable method to get the functionality back within a TB session, is the "disable/enable add-on". 
Otherwise, the issue still persists. I'll keep you posted about any status changes.

**Comment by speedball2001** [comment]
I tried something. Could you test the version attached to this comment and let me know if it fixes the issue or not? Please unzip the file and install the xpi file.

[ic.zip](https://github.com/speedball2001/identitychooser-mx/files/5403666/ic.zip)

**Comment by ienae** [comment]
Hi Speedball, I just installed your test version after having first removed the old version and fully restarted TB. Unfortunately no changes. :-(   
Besides this, the "disable/enable method" still works. 
Could there be some bad interaction with another add-on since the TB version update? 
Thank you for working on this issue. It would be great to make this work. 

PS: currently, I am very busy, but once I have a bit more time, I think of setting up a fresh TB78 with all the add-ons on another system to see, if the same issue comes up there as well. So far, I have not updated my other TB machines, since I can not afford any more problems on my e-mail clients.

**Comment by speedball2001** [comment]
>  Could there be some bad interaction with another add-on since the TB version update?

This is what I suspect, to be honest. What I did in my change was to make sure to run Identity Chooser's initialization after Thunderbird's main window is fully loaded. 

I understand that you need to keep your installation working. The only way to find out what causes the issue would be to disable every addon except Identity Chooser and selectively enable one addon after the other while restarting Thunderbird after every change.

**Comment by hopalongrock** [comment]
It still works fine for me, with this ic.zip too, ever since I disabled and enabled all of my addons.

**Comment by ienae** [comment]
I think, that the idea with the colliding add-ons was right!  
It seems, that the PGP Enigmail add-on causes the trouble. Since I disabled this one, IC works like a charm again. I can reproduce the problem, when I re-enable Enigmail and have the same issues as before. 
For the moment, I can live without Enigmail, but it would be interesting to find the true cause of that problem. 
Could it be, that different Enigmail settings for different accounts/identities make the IC add-on run to function incorrectly?

**Comment by speedball2001** [comment]
I haven't used Enigmail. I'll have to look into it. Wasn't enigmail supposed to be phased out in favor of OpenPGP natively integrated into TB itself?

**Comment by hopalongrock** [comment]
Unfortunately now Identity Chooser 2.0 (ic.zip) doesn't work again.
Here are my addons downloaded and installed after ic.zip:
qnote-0.6.3-tb.xpi               2020.10.21 16:09
confirm_address-1.3.6-tb.xpi     2020.10.21  8:38
uBlock0_1.30.7b0.thunderbird.xpi 2020.10.20 14:23
ic.zip                           2020.10.20  7:54
I also enabled the Check and Send addon.

I removed uBlock and confirm_address, but no change

**Comment by hopalongrock** [comment]
I just found if I disable the Qnote addon, Identity Chooser works fine - if I enable it, Identity Chooser doesn't work.
Presumably its operation depends on the addon mix.

A similar problem is with the Toggle Message Pane addon, a disable and an enable helps, and the Preview button works, but only in the current TB session.

**Comment by speedball2001** [comment]
Could you install https://github.com/speedball2001/identitychooser-mx/releases/tag/2.1-beta and test again? In my development environment, QNote and that version work together.

**Comment by hopalongrock** [comment]
Qnote works fine with 2.1beta1. 

Hopefully this will stay the same after installing, uninstalling, enabling, disabling addons.

**Comment by Skeeve** [comment]
Same issue here. Only Addons to TB are:

DKIM Verifier
ImportExportTool NG
Identity Chooser

Disabling the other extensions make no difference. Write Button still does not invoke identity chooser.

**Comment by hopalongrock** [comment]
I gave up for now, it doesn't work again after installing some new addon versions.

**Comment by Skeeve** [comment]
I think I found a hint for solving the issue.

For two of my accounts I don't use password manager, so I have to enter the password each time I start TB.

I now stored their passwords and now IC's functinonality is back. No need to disable/enable.

@hopalongrock can you confirm that you have (for some accounts) no passwords stored? Does it work if you store them?

**Comment by hopalongrock** [comment]
I have all of my accounts stored, and I use Master/Primary password, I don't really want to change this.
My experience is that addon works or doesn't work depending on the installed addons, or their order.
Perhaps it would be better not to modify the original buttons but to use separate buttons.

**Comment by speedball2001** [comment]
@hopalongrock Do you see any error messages in Thunderbird's error log (Menu -> Tools -> Developer Tools -> Error Console?

**Comment by hopalongrock** [comment]
Here is the full error console after Disable - Enable - Restart (made by copy paste)

[full-error-console-after-restart.txt](https://github.com/speedball2001/identitychooser-mx/files/5546405/full-error-console-after-restart.txt)

**Comment by speedball2001** [comment]
OK, next try. I hop I found the cause. Could you please install https://github.com/speedball2001/identitychooser-mx/releases/tag/2.1beta2 and let me know if this fixes the issue for you?

**Comment by Skeeve** [comment]
For me it seems to work.

I removed my passwords from the store and the functionality of IC was gone.

Then I installed the beta2.

The functionality, even after a restart, is there.

Thanks a lot.

**Comment by hopalongrock** [comment]
I installed it, restarted, removed an addon, re-installed that, and now works.
Hopefully it will stay that way.
Thanks

**Comment by speedball2001** [comment]
@hopalongrock, @Skeeve Awesome. Believe it or not but the issue was caused by a bug in Thunderbird itself. I talked to one Thunderbird's addon developer support guys who pointed me in the right direction.

**Comment by hopalongrock** [comment]
Oh yeah, they're just people too.

**Comment by mMuck** [comment]
@speedball2001 So they correct this in a future update?
I'm on TB 78.5.1 (newest on release channel) and have the exact same issue. The work-around works too.

Didn't this Add-on has a coloring option? I miss this.
Anyway: Thanks for the great work. Not everyone keeps his add-on alive due to the big TB changes... 👍

**Comment by speedball2001** [comment]
@mMuck I have a workaround implemented that fixes the issue. I'll be available in the next version of Identity Chooser.

For coloring, please use https://addons.thunderbird.net/en-US/thunderbird/addon/bordercolors-d/. It is similar enough for me to not duplicate the code in Identity Chooser 2.

**Comment by Skeeve** [comment]
@speedball2001: Yesterday functionality disappeared after adding a new identity.

The usual workaround (disable, enable) helped.

**Comment by speedball2001** [comment]
I released 2.1beta4. I have everything implemented that I think may fix the issue. If it still occurs, I don't know.

**Comment by speedball2001** [comment]
I released Identity Chooser 2.1 and submitted the new version to addons.thunderbird.net. Version 2.1 fixes this bug.
