### ISSUE TITLE
identitychooser.xpi v3.0 not working with TB 78.x

### ISSUE THREAD

**Issue by SHC22** [speedball2001/identitychooser-mx#30]
Hi,
I am still using v2.2 and today I wanted to update to version 2.3/3.0. Unfortunately TB answered:
"Identity chooser could not be installed because it is not compatible with Thunderbird 78.13.0."

Is it only compatible with TB 91.x ?

Thanks, 
SHC

**Comment by speedball2001** [comment]
Version 3 is only for TB91. It's functionaly equivalent to 2.2 for TB78 except that it removed a couple of workaround for bugs in TB78.
