### ISSUE TITLE
Quoted text in Reply All is blank

### ISSUE THREAD

**Issue by jburton-trg** [speedball2001/identitychooser-mx#31]
On choosing a message with multiple recipients and clicking Reply All, the resulting message compose window is blank, no quoted text.
Include quoted text on replies is selected in Settings.
Works fine on single Reply, and Forward.
Works on Reply All with the extension disabled.

**Comment by speedball2001** [comment]
Did you update Identity Chooser to version 3.0?

**Comment by jburton-trg** [comment]
Yes, seems the issue remains.

**Comment by jburton-trg** [comment]
Possibly linked to? [https://github.com/speedball2001/identitychooser-mx/issues/28](url)

**Comment by Solwayuk** [comment]
Same issue
the "reply all" button will display blank email
im on TB 91.0.2

**Comment by speedball2001** [comment]
Hi,

could you please test the latest beta version 3.1beta1: https://github.com/speedball2001/identitychooser-mx/releases/tag/3.1beta1

Please let me know if it fixes the issue for you.
