### ISSUE TITLE
Auto choose non existing identity

### ISSUE THREAD

**Issue by Skeeve** [speedball2001/identitychooser-mx#32]
Is this possible?

My mail server allows me to choose my identity freely (i.e. the part before the @). So I usually, when filling out a form I give a "personalized" mail address like github @ mydomain.com.

It's very cumbersome to have to create a new identity for each of these cases and I tend to forget it before replying to a mail I received on such an address.

It would be great would the recipient address of a mail I received, if it matches * @ mydomain.com, be used as the sending identity.

**Comment by speedball2001** [comment]
I'm sure that an addon could implement this but doing things automatically is out of scope for Identity Chooser. The whole reason it exists is to take automatisms out of the picture when it comes to composing an email in Thunderbird.

**Comment by Skeeve** [comment]
Thanks for the reply.
