### ISSUE TITLE
Feature Request - Bold Text to Mark Current Mailbox when Answering Mails

### ISSUE THREAD

**Issue by xbluemonkx** [speedball2001/identitychooser-mx#33]
Hi there,

on the thunderbird addon website it is written that you prefer an email, but I am no way able to find an email address anywhere. Therefore I am posting my Feature Request here.

The Addon works perfect for me if I write a new email, but when I *answer* an email it happens from time to time, that I think it was sent to sent to mailbox A and choose mail A as sender whil it actually was written to mailbox B.

My feature request therefore is: If I click on "reply" or "forward" the maildress that that specific mail was sent to should be highlighted (e.g. shown as bold) so that I directly know which would be the correct mail to choose to answer from.

An alternative to this would be an option to disable the addon for "reply" / "forward" actions so that it only lets me choose the identiy whenever I start a new message, but uses the the mail that an email was sent to as a sender by default, when i reply / forward an email.

**Comment by xbluemonkx** [comment]
Hi,
great! did not know that the feature to disable it on reply / forward already exists.

Too sad that TB does not allow you to change the styling of the menu anymore.

As a workaround, I could imagine sth like this: Place the "correct" reply / forward mail on the very top of the context menu and add a horizontal line afterwards. With "horizontal line" I mean sth like those lines that group the main menu. e.g. if you click on "extras" there are seven groups). - I assume TB lets you define the order of the items and use standard objects like those horizontal lines?

**Comment by speedball2001** [comment]
> As a workaround, I could imagine sth like this: Place the "correct" reply / forward mail on the very top of the context menu and add a horizontal line afterwards. With "horizontal line" I mean sth like those lines that group the main menu. e.g. if you click on "extras" there are seven groups). - I assume TB lets you define the order of the items and use standard objects like those horizontal lines?

Identity Chooser let's you specifically define the order in which the identities displayed. Moving identities around based on the message receiver would clash with that. In fact, Identity Chooser's philosophy is: No automatisms, ever.

Plus, there are other addons out there that also manipulate the reply buttons and I have to be very careful not to mess with them.

In short: While I sympathize with your suggestion I wont implement it.

**Comment by xbluemonkx** [comment]
Hi,
thanks for your detailed explanation. I tottally understand and aggree with you that it does not make much sense once you know the limitations and boundaries.
