### ISSUE TITLE
Cursor stays on address line

### ISSUE THREAD

**Issue by jcm1948** [speedball2001/identitychooser-mx#36]
With the new update to Identity Chooser (on Firefox), when I click Reply, the cursor stays on the recipient's address line instead of dropping down to the message box. When I disable Identity Chooser, the cursor moves to the box. Any idea of what's going on?

**Comment by speedball2001** [comment]
Turns out that this is a bug in Thunderbird itself:

https://bugzilla.mozilla.org/show_bug.cgi?id=1732558

There's nothing I can do about.

As a workaround you could deactivate Identity Chooser's menu for the reply button in Identity Chooser's settings.
