### ISSUE TITLE
Signature not appearing

### ISSUE THREAD

**Issue by milivella** [speedball2001/identitychooser-mx#38]
Hi. Since I upgraded to Thunderbird 91 [1], when I click on "Write" and select an identity, the blank message that is opened has no signature, even if a signature is set up for that identity/account. If I click on the "From" field, select another identity and then select the original identity again, the signature appears. Thanks in any case for this wornderful add-on.

[1] More details:

- Exact Thunderbird version: Thunderbird 91.2.1 (32 bit)
- OS: Windows 7 Professional (64 bit)
- Previous Thunderbird version: unfortunately, I don't know, I guess 78

**Comment by speedball2001** [comment]
Which version of Identity Chooser do you have installed?

**Comment by milivella** [comment]
Version 2.2 (last update: 2021-01-27). Thanks for the reply.

**Comment by milivella** [comment]
Oh, I see. I updated it to 3.1 and it works. Sorry for wasting your time!
