### ISSUE TITLE
Missing option in sender drop down box

### ISSUE THREAD

**Issue by hofrichter** [speedball2001/identitychooser-mx#4]
It is a great thunderbird addon, but it removes to posibillity to edit the sender address.
There is such an option in pure thunderbird, but get lost, as soon as you enable the plugin. It would be great, to find a way, making the sender address editable.

**Comment by speedball2001** [comment]
Is this happening with Identity Chooser 2.x in TB78 or is this an issue with earlier versions of the addon/thunderbird?

**Comment by speedball2001** [comment]
I can't reproduce this in Thunderbird 78 and Identity Chooser 2.1.
