### ISSUE TITLE
[Feature request] Take over colors from "Border Colors" into popup menu

### ISSUE THREAD

**Issue by bege10** [speedball2001/identitychooser-mx#40]
Hello,
is it possible to take over the colors from the add-on "Border Colors" into the popup menu of your add-on? I have quite a number of identities and it would be helpful if the entries would be colored as they are in the popup menu for the tags.

![Screenshot_290](https://user-images.githubusercontent.com/1184237/140165294-223fda41-7b17-47a4-861d-e0b9e5aa3c50.png)

**Comment by speedball2001** [comment]
While this is a good idea it's not possible to implement. Firstly, settings are private to addons which means that Identity Chooser can't access BorderColors' settings. Secondly, with Thunderbird's move from addons to mail extensions it lacks an API to style menus.
