### ISSUE TITLE
TB 91.6.2 (64-bit): Opening an attached email (.eml attachment) in a separate window Identity Chooser disables reply for this mail and all following reply attempts to all other emails

### ISSUE THREAD

**Issue by Cluster15-2** [speedball2001/identitychooser-mx#44]
Hi,

in line with some other issues re the recent Thunderbird releases in combination with Identity Chooser: 

If I open an attached email in a separate window the reply button there does not work. Moreover, after that any other attempt to reply to any mail also fails until the add-on is disabled and re-enabled or TB is restarted. 

TB 91.6.2 (64-bit) under Linux, Identity Chooser 3.1

**Comment by jnmills** [comment]
I have experienced this too.

TB 102.5.0, Windows 10, Identity Chooser 3.2.

Was much more generic:

- Open message A with right-click "Open in New Window".
- (move it clear)
- Click on an other message in the TB Message list
- Click Reply in the main TB window
- The Reply window opens but is populated with details from message A, not message B as you would expect.
- (Dismiss the reply window)
- If you close the popup for message A
- Reply to message B - no reply window appears
- Need to restart TB to reinstate behaviour
The unexpected behaviour only seems to occur with "New Window" and not with "New Tab"

**Comment by speedball2001** [comment]
This should fixed with Identity Chooser 4.0.
