### ISSUE TITLE
TB102 multiple messages opened for reply when using Reply or Reply-All

### ISSUE THREAD

**Issue by ciscoqid** [speedball2001/identitychooser-mx#48]
Since updating to TB102 (somewhat unintentionally), I have found that with Identity Chooser active, using Reply or Reply-All on a message opens windows for that message and one or more other messages, apparently randomly.  I was not sure if it was due to the extension, but after I disabled it, Reply/Reply-All opens just the intended message window for reply. Happy to engage in a shared Zoom or similar to demonstrate if needed.

**Comment by biltong11** [comment]
I am having the same issue. Also proven by disabling the extension. When I hit reply for a single message, a reply window opens for each of the open tabs that I have at that time.

**Comment by speedball2001** [comment]
Could you please install the new [beta version 3.2beta1](https://github.com/speedball2001/identitychooser-mx/releases/tag/3.2beta1) and report back if it fixes the issue for you?

**Comment by biltong11** [comment]
Thank you!
Initial tests suggest this has worked.
Thank you for the quick response.

**Comment by speedball2001** [comment]
Fixed in version 3.2.
