### ISSUE TITLE
Pre select an identity

### ISSUE THREAD

**Issue by elysch** [speedball2001/identitychooser-mx#49]
Thanks for the add-on it's very useful.

I've just downloaded today. I'm not sure if what I'm going to suggest happens if de-select an option like " Show List of Identities When Clicking on Reply button". Sorry if it does, maybe it's just a matter of changing a label to clarify it.

Now, my suggestion:
I would just make a change. Very important change for me since I happen to have many identities, so it's not comfortable for me to always choose from a lot of options.

It would be great if it could compare the reply email from, to, cc or bcc (maybe) for a mail addresses that matches the list of possible identities and put it separately at the beginning of the list or simply just select that one.

If none matches, then do ask and let the user decide.

---- EDIT ----
And, for new messages, let the user choose a default identity, and put it at the beginning of the list the same way: separated if possible.

Again. Thanks for the great work.

Ely

**Comment by speedball2001** [comment]
Hi,

you can sort your identities in Identity Chooser's settings and move your default identity to the top of the list.

As for pre selecting the identity on replying -- that's the kind of automation that Identity Chooser avoids. The addon is all about forcing the user to make an explicit choice. In other words: I understand your feature request but it is not compatible with Identity Chooser's "philosophy".

I suggest you deselect the option "Show List of Identities When Clicking on Reply Button". In that case, Identity Chooser doesn't interfere with replying at all. As far as I konw, Thunderbird does choose the recipient of an email as the sender of the reply.

**Comment by elysch** [comment]
Oh. I see.

Thunderbird is not helping me with that because the account I'm replying from is not the same as the one that has the identity. 

You're right by thinking if it selects for you, it is prone to make mistakes.

Ok. What if the "pre-select" just highlighted any match and opens the same selector?.

**Comment by elysch** [comment]
Making more tests... I found this:

The Identity Chooser is enabled

If I click on "write" button, it asks to select an identity (Ok) (And I now have at the top the one I normally want, thanks)

If I reply to a message for the one I have an exact identity, it selects the right one, even if it's from another account. (Ok)

The problem comes when I reply to one that I don't have a specific identity configured. It just takes the one of the account I'm reading from. That's not ok for me. I would like Identity Chooser to force me select an identity in the compose window.

Is it possible?

Thanks again.

**Comment by elysch** [comment]
One more thing.

Now I see... I right clicked the email on the list of emails, then selected "reply". That's why Identity Chooser didn't ask for an Identity.

It would be better for me if the Identity was asked in the compose window. Since that way no matter what method I use to reply, there's no risk of using the wrong identity. Better yet if the existing identity in the from, to, cc, bcc has some color in the list to ease of use.

Even better for me, if the selector is opened only when the from, to, cc, bcc doesn't have an exact match for a configured and enabled identity on any account; instead of asking every time.
Is that completely out of the question?. 

Thanks.

**Comment by elysch** [comment]
Also, when you click on a mailto: link, it opens directly a compose window. Another reason to make Identity Chooser force the user to select on that window.
:)

**Comment by speedball2001** [comment]
You know, Identity Chooser 2.x which was implemented before addons had to be ported to the new MailExtension model did most of what you're asking for: It extended the menus, mailto links. It even hooked into Thunderbird's address book.

Unfortunately, MailExtensions don't provide APIs for that anymore. Identity Chooser 3 does what it does using the APIs that are available. Anything more than that involves hackery that I don't have the time to do.

It is what it is.
