### ISSUE TITLE
Sender-selection drop-down menu does not show up on buttons in message window

### ISSUE THREAD

**Issue by gamut-gc** [speedball2001/identitychooser-mx#5]
Thanks for bringing the Identity Chooser back to Thunderbird 78!

There seems to be a slight oddity though - or, I do not know how to
bring it to work.

The add-on works fine, when using the Send/Reply-To/Forward buttons from
Thunderbird's main window - a small pop-up with the configured
sender-emails appears and I can select the wanted sender-address from there.

When I open an email in a separate window (by double clicking it) and
use the Send/Reply-To/Forward buttons from that window, the pop-up with
the configured sender-emails does not appear.

I am pretty sure that the above behaviour was supported in previous
versions of the add-on, but with the latest version it seems I am unable
to configure it.

I am using
Thunderbird version TB 78.4.0 (32-Bit)
Identity Chooser version: 2.0

**Comment by speedball2001** [comment]
I fixed this issue in version 2.1beta. Please download it from the [release section](https://github.com/speedball2001/identitychooser-mx/releases/tag/2.1-beta)  and let me know if it works for you.

**Comment by Skeeve** [comment]
I tried to install but FireFox prevents me to do so because it's not signed.

**Comment by elhennig** [comment]
It works for compose, but not for "answer", "answer to all" or "forward"

**Comment by speedball2001** [comment]
@elhennig There are two different issues that fit what you describe:

* https://github.com/speedball2001/identitychooser-mx/issues/3 if it doesn't work on message header buttons
* https://github.com/speedball2001/identitychooser-mx/issues/12 if it doesn't work in Thunderbird's main tool bar buttons.

**Comment by elhennig** [comment]
I use the 2.1 beta2 and the dropdown does not appear on the Reply-To and the Reply-To-All button, only on the Compose. Should this also work as in the TB68 version that the list pops up when using the keyboard shortcuts?

**Comment by speedball2001** [comment]
@elhennig Could you please open a new issue for the keyboard shortcuts. The issue you're commenting on here is for the missing functionality in stand alone message view windows.

**Comment by speedball2001** [comment]
@gamut-gc Could you test version 2.1beta4 and confirm that the issue is fixed?

**Comment by speedball2001** [comment]
I released Identity Chooser 2.1 and submitted the new version to addons.thunderbird.net. Version 2.1 fixes this bug.
