### ISSUE TITLE
large number of identities can not be used anymore

### ISSUE THREAD

**Issue by poisonnuke** [speedball2001/identitychooser-mx#53]
I have over 40 identities in TB, and until 3.1 that was working fine. Now the list is limited to 20ish(?), therefore I'm not able to choose the correct identity anymore when replying and creating an email.

**Comment by speedball2001** [comment]
Could you please check if you have every identity enabled in Identity Chooser's settings?

Also: If you open Thunderbird's error console after startup, you should find debug statements from Identity Chooser. Do they show only 20 identities or all identities?

**Comment by poisonnuke** [comment]
In order to send my mails I deleted a lot of identities, so I was able to see the one I needed in the list.
Now that I have recreated all entries, the list is actually working. So I cannot reproduce the error any longer.

From what I can recall, the list in the options menu didnt show all entries either. So maybe after the update TB had some issues with some of my identities. I will close this request as it is not clear whether is an TB related issue or  not.
