### ISSUE TITLE
When right clicking a recipients email address, no identity selection is offered

### ISSUE THREAD

**Issue by MoralCode** [speedball2001/identitychooser-mx#54]
1. open an email with multiple recipients
2. select a recipient, right click their name/email
3. select "compose message to"
expected: it would be nice to have a choice over which account is used to send that email
actual: it just uses the default account and identity you have configured in thunderbird.

Is this something thats solveable? or it it more like #41 in that its not something that is available in the thunderbird API?

**Comment by speedball2001** [comment]
This is fixed in Identity Chooser 4.0.
