### ISSUE TITLE
I use two different IDs to switch between ASCII and HTML composer, something TB still is not able to do. The new ID chooser does to switch the edit mode when choosing the appropriate ID. Can this be changed to the behavior with TB 102?

### ISSUE THREAD

**Issue by speedball2001** [speedball2001/identitychooser-mx#58]
I use two different IDs to switch between ASCII and HTML composer, something TB still is not able to do. The new ID chooser does to switch the edit mode when choosing the appropriate ID. Can this be changed to the behavior with TB 102?

_Originally posted by @elhennig in https://github.com/speedball2001/identitychooser-mx/issues/57#issuecomment-1659886733_

**Comment by elhennig** [comment]
As I wrote I was not able to switch the message editor between ASCII and HTML, other than by using to IDs. With  ID chooser I could then choose the correct ID wether I wanted to reply in ASCII or HTML, respectively.
With the latest beta on TB 115 I can only choose which ID to use after the editor window pops up and then the editor is set to whatever format the default ID uses to compose.

**Comment by speedball2001** [comment]
Can't you just Shift-Click on "New Message" or "Reply" etc. to switch between your default format and the other one?

**Comment by elhennig** [comment]
I was actually not aware of that possibility. Thanks for your hint. As it worked until today, I had no urge to find another solution ;-)

Still, it would be nice, if the composer window would only start up after choosing the ID and open it with the configured default format.

**Comment by speedball2001** [comment]
> Still, it would be nice, if the composer window would only start up after choosing the ID and open it with the configured default format.

I get that but, unfortunately, that's not possible anymore. I liked the old way as well but the API doesn't support it.

**Comment by WithThisHerring** [comment]
> Can't you just Shift-Click on "New Message" or "Reply" etc. to switch between your default format and the other one?

Would you consider adding this to the Readme in Github and also the description on the TB addon website?  I use a lot of shortcuts and had never heard of this; I think this will be very useful to everyone who uses your great addon.  :)

**Comment by speedball2001** [comment]
Shift-Click is a standard Thunderbird shortcut that's been available in Thunderbird at least for 10 years if not more. It's documented under [Message functions](https://support.mozilla.org/en-US/kb/keyboard-shortcuts-thunderbird#w_message-functions).
