### ISSUE TITLE
Lost ability to choose identity.

### ISSUE THREAD

**Issue by griffinit99** [speedball2001/identitychooser-mx#60]
Since Thunderbird did a massive upgrade the Get Messages has no identities to choose, nor do write or reply. Basically the functionality of this add-on has disappeared. I am amazed at how much I miss it.

**Comment by speedball2001** [comment]
What version of Identity Chooser do you have installed? Which version of Thunderbird? Do you notice that starting with version 4, Identity Chooser does work differently? The list of identities is now shown on top of the editor:

![identitychooser-light](https://github.com/speedball2001/identitychooser-mx/assets/2027437/f27a4313-f6d0-4a98-815c-cee16f2b7c59)
