### ISSUE TITLE
Identity sorting

### ISSUE THREAD

**Issue by jandoemen** [speedball2001/identitychooser-mx#61]
Hi, 

I use the catch-all plugin with a catch-all domain (for spam reasons). Every time I have to provide an e-mail address, I make up a new one (like: github.identity.chooser@catchdomain.be). The catch-all add-on creates a new identity every time en new address is used so I have hundreds of identities and sorting them with drag & drop seems not the best solution.

Is there a way to sort identities other than drag & drop? Is the sort order kept in an accessible place (file)? Can you include this in your add-on? I saw that there are more people with this request.

Thanks fro your answer, Jan

**Comment by speedball2001** [comment]
There's currently no way to sort the identites other than with drag and drop.
