### ISSUE TITLE
Recipient list changes

### ISSUE THREAD

**Issue by g-tc** [speedball2001/identitychooser-mx#62]
Hard to explain, so I'll do it by example...

I monitor two identities:

- me@me.com  = my main address

- them@them.com  = an address I monitor for the actual account holder

When I get an incoming email addressed to both:

    From: x@x.com
    To: y@y.com, them@them.com, me@me.com

I click Reply to All:

    From: them@them.com
    To: x@x.com, y@y.com, me@me.com

There are *two* problems with the reply.  First, it's the wrong "From" address and second, it removed the wrong address from the list of recipients.  Identity Choose currently only solves the first.

That is, when I use Identity Chooser to force the From address to my main address, the resulting reply looks like this:

    From: me@me.com
    To: x@x.com, y@y.com, me@me.com

Notice that them@them.com is missing from the recipients, while me@me.com is still there.  Strictly speaking I guess this is a Thunderbird bug/problem rather than an Identity Chooser problem, but if Thunderbird had been inclined to fix multiple identity issues then they'd have done it long before now and Identity Chooser would not be needed.

**Comment by speedball2001** [comment]
To be honest, I don't know what Identity Chooser should do about this. If I was you, I'd open a ticket with Thunderbird directly.

**Comment by g-tc** [comment]
Thanks for your response.  I'll consider a Thunderbird ticket, but I suspect it will be a hard sell there, because the problem is only applicable when you are trying to make Thunderbird better at handling multiple accounts, and I've seen no sign they are inclined to do that (otherwise this and similar projects would not exist).

Your response was not unexpected, but since I didn't know what was involved so I thought I'd ask.  If you want to close this as "Won't Fix" I am fine with that.
