### ISSUE TITLE
Suggestion: Signature editor

### ISSUE THREAD

**Issue by LinuxOpa** [speedball2001/identitychooser-mx#65]
US:
First of all THANK YOU for the addon!
Suggestion: The possibility of editing the signature in the addon, optionally with html editor, because the mini editor in Thunderbird is old-fashioned to say the least...

DE:
Zunächst DANKE für das Addon!
Vorschlag: Die Möglichkeit der Bearbeitung der Signatur im Addon, optional gleich mit html-Editor, denn der Minieditor in Thunderbird ist gelinde gesagt altbacken...

**Comment by speedball2001** [comment]
It's a good idea and I feel your pain but this is out of scope for Identity Chooser.
