### ISSUE TITLE
Translation into Italian

### ISSUE THREAD

**Issue by topoldo** [speedball2001/identitychooser-mx#66]
Hi Janek.
How can I submit to you my translation of identitychooser into Italian (ie /locales/it/messages.json)?
Regards
Topoldo/Leopoldo

**Comment by speedball2001** [comment]
Thank you for taking the time to translate everything. Please attach the file to this issue.

**Comment by speedball2001** [comment]
Thank you. I'll add it to the next version.

**Comment by speedball2001** [comment]
I made a new release with italian localization. Again, thank you for the translation.
