### ISSUE TITLE
Shortcut functionality is broken

### ISSUE THREAD

**Issue by Rohit-NZ** [speedball2001/identitychooser-mx#68]
Examples

1. Main Menu File.New (Ctrl-N) works when selected but hotkey no longer works
2. If two windows (emails) are open, Ctrl-N works on the last one open.  if that is closed, it doe not work on the previous one.

**Comment by speedball2001** [comment]
Could you please provide more information? Which version of Identity Chooser do you use? Which version of Thunderbird?
