### ISSUE TITLE
Position of Signature

### ISSUE THREAD

**Issue by Rohit-NZ** [speedball2001/identitychooser-mx#69]
For replies, it puts the new signature at the bottom of the email, even though it removes the previous signature between the new email and the reply quote.  This makes it totally useless for me.

I prefer the signature just after what I am typing, so they can see who its from.  The rest of the to-and-fro of past emails should come after that.

Signature Switch manages it, so its doable.

**Comment by speedball2001** [comment]
Position of the signature is controlled by the account not by Identity Chooser. Identity Chooser simply opens an editor and lets Thunderbird do its job afterwards.

I suggest that you check the accounts setting for composing for what's configured for signature placement.
