### ISSUE TITLE
French translation proposal

### ISSUE THREAD

**Issue by DenB10** [speedball2001/identitychooser-mx#71]
Hi,

I don't know how to suggest a French translation of Identity Chooser.
I'm sending it here as an attachment.
Best regards

[messages.json](https://github.com/speedball2001/identitychooser-mx/files/15308631/messages.json)

**Comment by speedball2001** [comment]
Thank you. I'll include it in the next release.

**Comment by speedball2001** [comment]
I merged your pull request. Thank you for providing the translation.
