### ISSUE TITLE
Select email profile where the extension is used

### ISSUE THREAD

**Issue by beastybeast** [speedball2001/identitychooser-mx#74]
Why is it not possible to select a single (or more) email account where the extension is in effect. A common situation is that you have multiple profiles/accounts and only need it for one of them. But for some reason I need this extra step for all accounts.

**Comment by speedball2001** [comment]
Identity Chooser's idea is to force the user to manually choose the sender address as the first step when composing an email. To exclude one or more accounts would be against the goal of the addon.

Maybe I don't understand what your trying to achieve. Maybe you could elaborate.
