### ISSUE TITLE
Select account/profile to use based on the TO field

### ISSUE THREAD

**Issue by beastybeast** [speedball2001/identitychooser-mx#75]
Can the extension not select the account/profile to use based on the to field of the source email. Will really be a power feature and save some work for the user.

**Comment by speedball2001** [comment]
That's not a planned feature. The idea of Identity Chooser is to force the user to _manually_ select the sender address and go from there. Identity Chooser doesn't have and wont have any automatisms. I sympathize with this feature but Identity Chooser is not the addon for it.
