### ISSUE TITLE
ATN review: tabs and activeTab permissions are probably not needed

### ISSUE THREAD

**Issue by speedball2001** [speedball2001/identitychooser-mx#9]
From ATN's review:
The tabs and activeTab permissions are probably not needed and an add-on may not request permissions it is not using. The activeTab permission gives you access to the content of a (webpage-) tab and the tabs permission gives you access to some security related information like the URL of a tab. You do not need the tabs permission just to use the tabs API.

**Comment by speedball2001** [comment]
Fixed with 2.1beta.

**Comment by 7wells** [comment]
Hello! But is it relevant to have taken that out, as identitychoser-mx (version 2.2) requests "[full, unrestricted access to Thunderbird, and your computer](https://support.mozilla.org/de/kb/permission-request-messages-thunderbird-extensions#w_have-full-unrestricted-access-to-thunderbird-and-your-computer)"?

**Comment by speedball2001** [comment]
Well, the permissions tabs and activeTab were declared in Identity Chooser's manifest but not used. The reviewer requested to remove them, which I did because Identity Chooser doesn't need them.

As for "full, unrestricted access to Thunderbird, and your computer": Identity Chooser does not, in fact, accesses your files or anything on your computer outside of Thunderbird.

This warning is a byproduct of porting addons to the new Thunderbird mail extensions. Since mail extensions currently don't support everything addons such as Identity Chooser need (and were able to do in old versions of Thunderbird), addons need to implement so-called experiments. Any addon that implements an experiment gets full unrestricted access to the user's computer including file system access. This was already the case in earlier Thunderbird versions even though it wasn't spellt out like that.
